language: r

repos:
  CRAN: https://cloud.r-project.org
  molgenis: https://registry.molgenis.org/repository/R/
  datashield: http://cran.datashied.org/

cache:
  packages: yes

before_install:
- R -e "install.packages('dsBaseClient', repos = 'http://cran.datashield.org')"

matrix:
  include:
  - os: linux
    r: release
    script:
      - R CMD build . --compact-vignettes=gs+qpdf
      - R CMD check *tar.gz --as-cran
