language: r

repos:
  CRAN: https://cloud.r-project.org
  molgenis: https://registry.molgenis.org/repository/R/
  datashield: http://cran.datashield.org/

addons:
 apt:
   packages:
   - libharfbuzz-dev 
   - libfribidi-dev

cache: 
  apt: true
  packages: true

before_cache: 
  - Rscript -e 'remotes::install_cran("pkgdown")'
  - Rscript -e 'remotes::install_cran("usethis")'
  - Rscript -e 'remotes::install_cran("devtools")'

deploy:
  - provider: script
    script: Rscript -e 'pkgdown::deploy_site_github(ssh_id = Sys.getenv("TRAVIS_DEPLOY_KEY", ""))'
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: .ci/release.sh
    on:
      branch: master

