trigger:
- master

pr:
- master

jobs:  
  - job: RPipeline
    pool:
      vmImage: 'ubuntu-latest'
    container:
      image: 'rocker/tidyverse:latest'
    steps:
    - task: Bash@3
      displayName: Build R package
      inputs:
        filePath: .azure/build_r_package.bash
        failOnStderr: true
      env:
        GITHUB_TOKEN: $(GITHUB_TOKEN)
        R_LIBS_USER: '$(Agent.BuildDirectory)/R/library'

  
