trigger:
- master

pr:
- master

variables:
  job_name: $(Build.RepositoryName)

jobs:  
  - job: RPipeline
    pool:
      vmImage: 'ubuntu-latest'
    container:
      image: 'rocker/tidyverse:latest'
    steps:
    - task: Bash@3
      displayName: 'Prepare R-package ${{ variables.job_name }}'
      inputs:
        filePath: .azure/prepare.bash
        failOnStderr: false
      env:
        R_LIBS_USER: '$(Agent.BuildDirectory)/R/library'
    - task: Bash@3
      displayName: 'Check R-package ${{ variables.job_name }}'
      condition: eq(variables['Build.Reason'], 'PullRequest')
      inputs:
        filePath: .azure/pullrequest.bash
        failOnStderr: true
      env:
        R_LIBS_USER: '$(Agent.BuildDirectory)/R/library'
        CODECOV_TOKEN: $(CODECOV_TOKEN)  
    - task: Bash@3
      displayName: 'Release R-package ${{ variables.job_name }}'
      condition: ne(variables['Build.Reason'], 'PullRequest')
      inputs:
        filePath: .azure/release.bash
        failOnStderr: true
      env:
        R_LIBS_USER: '$(Agent.BuildDirectory)/R/library'
        CODECOV_TOKEN: $(CODECOV_TOKEN)  
        GITHUB_TOKEN: $(GITHUB_TOKEN)
        
